version: '3.8'

services:
  postgres:
    image: postgres:latest
    hostname: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    image: app
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    environment:
      SQL_CONNECTION_STRING: postgres://postgres:12345@postgres:5432/db?sslmode=disable
    command: /usr/local/bin/migrate
    depends_on:
      postgres:
        condition: service_healthy

  server:
    image: app
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    environment:
      SQL_CONNECTION_STRING: postgres://postgres:12345@postgres:5432/db?sslmode=disable
      SECRET_KEY: CSkdNKipxfcmIp4A3OHaPw==
      ACCESS_TOKEN_DELAY: 10m
      LISTEN_ADDR: :8080
    command: /usr/local/bin/server
    ports:
      - "8080:8080"
    depends_on:
      - migrate

volumes:
  pg_data:
